name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tag commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a "v${{ github.run_number }}" -m "Release ${{ github.run_number }}"
        working-directory: ${{ github.workspace }}
        if: success()

      - name: Push tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
        if: success()

      - name: Archive resource pack
        run: |
          zip -r adult_education_resources_v${{ github.run_number }}.zip . -x "*.git*"
        working-directory: ${{ github.workspace }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            adult_education_resources_v${{ github.run_number }}.zip
          tag_name: "v${{ github.run_number }}"
          prerelease: false
